%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This script creates a table with both epoch and non-epoch variables%
% - Input: Is generated by N19_ExtractAllData                        %  
%                                                                    %
% - Output: Table strucutre T                                        %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


N19_ExtractAllDat%a


groupOrder={'AbruptNoFeedback','FullAbrupt','Catch'};
%groupOrder={'Catch'};
colcodes=[0.6 0 0.6;0.8 0 0;0.2 0.2 1;0.6 0.6 0.6;0.9 0.9 1];%DO NOT TOUCH!!


nsub=10;%assume 10 subs per group

groupInd=NaN(1,length(groupOrder));
for i=1:length(groupOrder)
    tempInd = strfind(groupsnames,groupOrder{i});groupInd(i) = find(not(cellfun('isempty', tempInd))); 
    
end

%generate table
T=table;
dt=repmat(groupOrder,nsub,1);
T.group=nominal(dt(:));clear dt


for e=1:length(names)
    for p=1:length(params)
        dt=[];
        for g=1:length(groupOrder)
            %tempInd = strfind(groupsnames,groupOrder{groupInd(g)});Ind = find(not(cellfun('isempty', tempInd)));
            dt=[dt;squeeze(groupOutcomes{groupInd(g)}(p,e,:))];
        end
        eval(['T.',params{p},'_',names{e},'=dt;'])
        clear dt
    end
end

for p=1:length(params2)
    dt=[];
    for g=1:length(groupOrder)
        %tempInd = strfind(groupsnames,groupOrder{g});Ind = find(not(cellfun('isempty', tempInd)));
        dt=[dt;NonEpochoutcome{groupInd(g)}.par{p}];
    end
    eval(['T.',params2{p},'=dt;'])
    clear dt
end


