%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This script creates a table with both epoch and non-epoch variables%
% - Input: Is generated by N19_ExtractAllData                        %  
%                                                                    %
% - Output: Table strucutre T                                        %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%N19_ExtractAllData


groupOrder={'FullAbrupt','TMFullAbrupt','AbruptNoFeedback','TMAbruptNoFeedback'};
%groupOrder={'Catch'};
colcodes=[0.6 0 0.6;0.8 0 0;0.2 0.2 1;0.6 0.6 0.6;0.9 0.9 1;0.3 0.3 0.3;0 1 1];%DO NOT TOUCH!!


%nsub=10;%assume 10 subs per group

groupInd=NaN(1,length(groupOrder));

for i=1:length(groupOrder)
    tempInd = regexp(groupsnames,['^',groupOrder{i}]);groupInd(i) = find(not(cellfun('isempty', tempInd))); 
    nsub=length(groups{groupInd(i)}.adaptData);
    if i==1
        subcodes=cellstr(repmat(groupsnames{groupInd(i)},nsub,1));
    else
    subcodes=[subcodes;cellstr(repmat(groupsnames{groupInd(i)},nsub,1))];
    end
end

%generate table
T=table;
T.group=nominal(subcodes);

for e=1:length(names)
    for p=1:length(params)
        dt=[];
        for g=1:length(groupOrder)
            nsub=length(groups{groupInd(g)}.adaptData);
            dt=[dt;squeeze(groupOutcomes{groupInd(g)}(p,e,1:nsub))];
        end
        eval(['T.',params{p},'_',names{e},'=dt;'])
        clear dt
    end
end

for p=1:length(params2)
    dt=[];
    for g=1:length(groupOrder)
        %tempInd = strfind(groupsnames,groupOrder{g});Ind = find(not(cellfun('isempty', tempInd)));
        dt=[dt;NonEpochoutcome{groupInd(g)}.par{p}];
    end
    eval(['T.',params2{p},'=dt;'])
    clear dt
end


